### ISSUE TITLE
[super initialize];

### ISSUE THREAD

**Issue by colasjojo** [layervault/LVDebounce#6]
Why don't you call `[super initialize]` in `initialize`?

**Comment by codecaffeine** [comment]
You don’t need to according to the [docs](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSObject_Class/index.html#//apple_ref/occ/clm/NSObject/initialize) because the runtime already send the message to the superclass:
> The runtime sends the initialize message to classes in a thread-safe manner. Superclasses receive this message before their subclasses.

Apple used to explicitly say to not call super, now they say the super class may be called multiple times.

**Comment by colasjojo** [comment]
+1

**Comment by colasjojo** [comment]
Hi @codecaffeine. This pod has inspired a pod (not pushed yet). https://github.com/colasjojo/CBDActionBlocker
